version: "3"
services:
  mockapi:
    container_name: scrabble-mock-api
    image: elderops/scrabble-mock-api:latest
    ports:
      - "3000:3000"
    links:
      - solution-one
      - solution-two

  solution-one:
    container_name: scrabble-solution-one
    build: ./solution-one
    ports:
      - "3001:3001"
    environment:
      API_URL: http://mockapi:3000

  solution-two:
    container_name: scrabble-solution-two
    build: ./solution-two
    ports:
      - "3002:3002"
    environment:
      API_URL: http://mockapi:3000
